### ISSUE TITLE
onExit is automatically firing 

### ISSUE THREAD

**Issue by irtaza9** [HiDeoo/intro.js-react#100]
### Describe the bug

I'm using intro.js wrapper for React js in functional components. I'm was debug the component and every time my component renders the onExit callback automatically fired by the library.

### To Reproduce

This should be like onChange event or onComplete event, when someone interact with the exit/skip button the event should be call at that time.

### Expected behavior

I think this should be resolved in next PR 

### How often does this bug happen?

Every time

### System Info

OS: Windows (10)
Browser: Chrome
Version 108.0.5359.125 (Official Build) (64-bit)

### Additional Context

I created a [codesandbox](https://codesandbox.io/s/dazzling-sun-401qvj?file=/src/components/TourTesting.jsx) with the behavior of library, you can check the code and add your valuable thoughts in it.

**Comment by HiDeoo** [comment]
To understand the issue, you can add a log to your `useMount` hook:

```ts
useMount(() => {
    console.log("> useMount");

    setdata({ ...data, run: true });
});
```

The console would log `> useMount` two times. 

This behavior is due to your usage of `<StrictMode>` in your `index.js` file that enables the following check:

- Your components will [re-render an extra time](https://beta.reactjs.org/reference/react/StrictMode#fixing-bugs-found-by-double-rendering-in-development) to find bugs caused by impure rendering.

To test this, you can remove the `<StrictMode>` wrapping your application in `index.js` to see the console logs only 1 time `> useMount` and 0 times the log in the `onExit` event handler.

Note that all of these checks are development-only and do not impact the production build.

**Comment by irtaza9** [comment]
Dear @HiDeoo, As we know that React. StrictMode is a tool that highlights potential issues in a programme that may occurs in future or by any other chance. Is there any other way that is more proficient and stable? I've to call API's to store the record on db level.

**Comment by HiDeoo** [comment]
> Dear @HiDeoo, As we know that React. StrictMode is a tool that highlights potential issues in a programme that may occurs in future or by any other chance. Is there any other way that is more proficient and stable? I've to call API's to store the record on db level.

Your API call will only be fired twice in development mode so that may not even be an issue. If your call is affecting the state, you can check the [new documentation regarding handling effects firing twice in development](https://beta.reactjs.org/learn/synchronizing-with-effects#fetching-data) which describe a way to avoid having the second call in development affecting the state a second time.

> @HiDeoo , can you please elaborate why onExit is triggered when onComplete callback is called + vice versa?

This is the default behavior of `intro.js` and `intro.js-react` is not doing anything fancy regarding these callbacks. You can check [my comment here](https://github.com/HiDeoo/intro.js-react/issues/76#issuecomment-1073015104) to get more details and a workaround provided by `intro.js-react` to figure out if the tour is complete or not when using only this callback.

**Comment by irtaza9** [comment]
@HiDeoo, First of all thank you for your fast and effective response, I'm facing another issue with the library regarding `import ` attaching the warring that is triggered in the console.

![image](https://user-images.githubusercontent.com/98938307/210225300-0728d50f-d0fb-4f97-8dc8-946f6f4fda1e.png)

`import "intro.js/introjs.css";
`
# node_module

![image](https://user-images.githubusercontent.com/98938307/210225511-36e764ac-c763-43bf-a3b1-c421ee27fb43.png)

# package.json

```
    "intro.js": "^6.0.0",
    "intro.js-react": "^0.7.1",
```

**Comment by HiDeoo** [comment]
Looks like the issue is related to `intro.js` from the error message that [some other people are still encountering](https://github.com/usablica/intro.js/issues/1595#issuecomment-1210174376).

**Comment by irtaza9** [comment]
do we need to install `intro.js` in react.js project for `intro.js-react` or `intro.js-react` is an independent from intro.js? like do we need to install `intro.js` or not?

**Comment by HiDeoo** [comment]
> do we need to install `intro.js` in react.js project for `intro.js-react` or `intro.js-react` is an independent from intro.js? like do we need to install `intro.js` or not?

This is specified in the [installation instructions](https://github.com/HiDeoo/intro.js-react#installation):

> Make sure to have [React](https://facebook.github.io/react/) & [Intro.js](http://introjs.com/) installed (they're peer dependencies) and the Intro.js CSS definitions [properly loaded](http://introjs.com/docs/getting-started/install) into your project.

**Comment by irtaza9** [comment]
@HiDeoo, Thank you for your time and knowledge. I got my all queries resolved.
