### ISSUE TITLE
Steps position not respected

### ISSUE THREAD

**Issue by skoch** [HiDeoo/intro.js-react#21]
When explicitly stating the steps `position`, no matter what value I pass in for `position` it seems not to respect said value. Moreover, setting the `tooltipPosition` for the `options` doesn't seem to have any effect either.

eg:
```javascript
const steps = [
  {
    element: 'div[data-coachmark="saved-step-1"]',
    intro: 'foobar',
    position: 'bottom-middle-aligned',
  },
  {
    element: 'div[data-coachmark="saved-step-2"]',
    intro: 'foobaz',
    position: 'bottom-middle-aligned',
  },
];
// ...
<Steps
  enabled={enabled}
  steps={steps}
  initialStep={initialStep}
  onExit={this.handleExit}
  onComplete={this.handleComplete}
  options={{
    hidePrev: true,
    hideNext: true,
    exitOnOverlayClick: false,
    showStepNumbers: false,
    tooltipPosition: 'bottom-middle-aligned',
    prevLabel: '&lt; Back',
    nextLabel: 'Next &gt;',
  }}
/>
```

Am I not doing this correctly?

**Comment by HiDeoo** [comment]
Just checked on the [demo](https://codesandbox.io/embed/o2A4gwXE3?hidenavigation=1) and I can repro with the exact same code but it looks you're not doing anything wrong.

Actually, just passing `right` instead of `bottom-middle-aligned` will work as expected.

Altho, we're not doing anything fancy with the position, we just pretty much pass it to `intro.js`. I've checked a little bit but it looks like it's an issue on their end as we pass the proper argument but they have a `_determineAutoPosition` which returns `bottom-left-aligned` when wanting `bottom-middle-aligned` or `bottom-right-aligned`.

https://github.com/usablica/intro.js/blob/b46bbcd8af46be2ae3b43aba850334b12ff03cdb/intro.js#L634-L636

There are several issues related to positioning on their Github, some recent, maybe one is related to your issue.

**Comment by skoch** [comment]
Thanks for the response. 

I tried the demo as well with success however if I resize browser the step will, at a certain point, switch to `bottom-middle-aligned`. I suppose mobile support is a different beast and the reality is that the lib is preforming its own logic to determine the best position ... even though we are explicitly stating that we want it to be `bottom` at all times.

Will peruse issues over there.

**Comment by HiDeoo** [comment]
Yeah, they "recompute" the position with their own logic no matter what except if the wanted position is `floating` if I remember correctly.

I can't check right now but I remember sometime ago seeing an issue or pull request to implement a way to always use the desired position instead of the recomputed one even if it wouldn't be the best fit but I don't know if this is now possible or not. That could be something to check too.

**Comment by evnp** [comment]
In case anyone comes across this in 2024+... we were able to work around it by setting the options `autoPosition: false`. Presumably this might have some adverse effects if tooltips would go off screen (fortunately not relevant in our use-case).
