### ISSUE TITLE
Intro box is half hidden, when placed on a flex navbar item at the end of the screen

### ISSUE THREAD

**Issue by ufo2mstar** [HiDeoo/intro.js-react#49]
Have some CSS overlap issues on the edge of the screen, 
but not sure if they are an introjs issue or issue with this react port

Will just open another issue to look into, just in case.. lemme know if you need a code sample @HiDeoo :

This is the right end of my screen: happens in a bunch of screensizes

![image](https://user-images.githubusercontent.com/2426264/101977845-22756c80-3c16-11eb-8ef3-5dd4dec8a024.png)

**Comment by HiDeoo** [comment]
I had lots of issues with positioning when using intro.js, most of the time it was either intro.js issues that I could avoid by tweaking their CSS from my own styles (or even by forking their lib and tweak some calculations), or my own CSS that would lead to weird results. 

I've setup [a small repro](https://codesandbox.io/s/introjs-react-navbar-wkocu?file=/pages/Home.jsx) of a navbar using flex, altho I didn't mange to reproduce.

<img width="601" alt="Screenshot 2020-12-12 at 10 40 05" src="https://user-images.githubusercontent.com/494699/101980538-6d1ed500-3c66-11eb-9b4b-73d33bd5bddd.png">

Regarding the React wrapper, it doesn't do itself anything related to CSS or positioning so I highly doubt the issue is on this side.

**Comment by ufo2mstar** [comment]
Yes @HiDeoo , definitely not on this lib side!
I'm realizing that introJs calculations are pretty static and do not support responsive design out of the box.

and thanks for putting up this quick [example](https://codesandbox.io/s/introjs-react-navbar-wkocu?file=/pages/Home.jsx) to test! :D
I solved this issue with a `position` attribute in the `steps`:

### Code:
```yml
steps: [
   ....
    {
      element: '#top-right-item',
      intro: '...',
      position: 'left',
    },
   ...
],
```
### Result:
![image](https://user-images.githubusercontent.com/2426264/102697263-39115a00-41fa-11eb-8e2f-eee34bd3a964.png)

**Comment by HiDeoo** [comment]
Glad you solved it. Thanks for providing your solution.
