### ISSUE TITLE
#intro.js-react with multi pages 

### ISSUE THREAD

**Issue by toolaugh** [HiDeoo/intro.js-react#5]
how to use intro.js-react with multiple pages

**Comment by HiDeoo** [comment]
I would say this depends a lot on the structure of your application and how you are handling pages, if you're using React Router, another router, etc.

Regarding triggering the navigation between multiple pages while using intro.js, it's gonna depend on the API of the router you're using but you could simply trigger the navigation using one of the many [callbacks](https://github.com/HiDeoo/intro.js-react#props) available as props like `onBeforeChange`, `onComplete `, etc. like:

```js
onBeforeChange = nextStepIndex => {
  if (nextStepIndex === 4) {
    // The next step is the step 4, we need to go to another page...
    // this.router.goToPage(anotherPage);
    // ...
  }
}
```

**Comment by toolaugh** [comment]
thank you @HiDeoo  I got it.

**Comment by BruceL33t** [comment]
@HiDeoo 

I just tried what you suggested, but the problem is that if you use redux router and do `dispatch(push('/myroute'))` then intro.js-react won't be able to attach hints to the div in that other page we're trying to redirect to. I also tried setting a setTimeout of say 5 seconds after the route dispatch, but it still didn't work. Any ideas?
