### ISSUE TITLE
onExit firing even on step completion

### ISSUE THREAD

**Issue by sambhav2612** [HiDeoo/intro.js-react#76]
Hello @HiDeoo, we are building a platform tour using this wrapper however, the `onExit` method is firing even after properly completing the steps with `onComplete` working normally.

Expected behavior:
- If the tour is closed midway, fire `exit` event
- If the tour is completed normally i.e., all steps traversed, fire `complete` event

**Comment by HiDeoo** [comment]
Thanks for the feedback.

It looks like I'm not doing anything fancy regarding these callbacks as they're directly used with the default intro.js callbacks ([onexit](https://github.com/HiDeoo/intro.js-react/blob/c34a2b78fc31e66a8fa9bb0b86e20bddf4966962/src/components/Steps/index.js#L222) & [oncomplete](https://github.com/HiDeoo/intro.js-react/blob/c34a2b78fc31e66a8fa9bb0b86e20bddf4966962/src/components/Steps/index.js#L227)) so the current behavior is the default one when using intro.js.

I don't like the idea of potentially changing the behavior of these callbacks and differ from the default behavior of intro.js (even tho I think I agree with your expected behavior), altho, I pass down the `stepIndex` in the `onExit()` callback (which is a difference between this wrapper & intro.js) so it's fairly easy to figure out if the tour is complete using only this callback.
